version: '3.8'

# Define todos los contenedores (servicios) que Docker va a levantar
services:
#Construccion de la base de datos
  mysql:
    image: mysql:8.0
    container_name: mysql-db #Nombre del contenedor
    environment:
      - MYSQL_ROOT_PASSWORD=root # Contraseña del usuario root de MySQL
    ports:
      - "3307:3306" #puerto 3307 en tu máquina → 3306 dentro del contenedor
                    #Usa 3307 para no chocar con el MySQL de Laragon que ya usa 3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - veterinaria-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./main
    container_name: eureka-server
    ports:
      - "8100:8100"
    networks:
      - veterinaria-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8100/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
#Construccion del Api Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      - EUREKA_URL=http://eureka-server:8100/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - veterinaria-net
#Construccion de Registro
  registro:
    build: ./Registro
    container_name: registro-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/Registro_Paciente?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8100/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - veterinaria-net
#Construccion de Empleados
  empleados:
    build: ./Empleados
    container_name: empleados-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/registro_empleados?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8100/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - veterinaria-net
#Construccion de Citas
  citas:
    build: ./Citas
    container_name: citas-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/Registro_Citas?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8100/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - veterinaria-net

# ===== RED INTERNA =====
#Esta parte es importante ya que permite que los contenedores se comuniquen entre si usando sus nombres
networks:
  veterinaria-net:
    driver: bridge

volumes:
  mysql-data: