server:
  port: 8100

spring:
  application:
    name: main

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8100/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0