spring:
  application:
    name: identificacion

  datasource:
    url: jdbc:mysql://localhost:3306/vet_identity_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8085

jwt:
  secret: este_es_un_secreto_muy_seguro_para_la_veterinaria_que_debe_ser_largo
  expiration: 86400000

empleados:
  service:
    url: http://localhost:8081

propietario:
  service:
    url: http://localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8100/eureka/