spring.application.name=Citas

spring.datasource.url=jdbc:mysql://localhost:3306/Registro_Citas
spring.datasource.username= root
spring.datasource.password= 

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled= true
spring.flyway.repeatable-sql-migration-prefix=true

server.port=8082

